SELECT * FROM actor;
SELECT first_name from actor;
SELECT last_name from actor;
select distinct first_name from actor;
select distinct first_name, last_name from customer;
SELECT address, postal_code from address where district = "England";
select * from film where rating="PG-13";
select * from film where replacement_cost>"11.99";
select * from film where length<60 or length>120;
select amount, payment_date from payment where payment_date >'2005-07-27 18:40:20' and amount <'4.99';
select title, description, length, rating from film where (length > 60 or length < 120) and rating="r";
Select * from film order by length asc;
select * from payment order by amount asc, payment_date desc;
select address from address where address is not null and postal_code is null;
select first_name from actor order by first_name limit 10;
select min(amount), max(amount) from payment;
select sum(amount) as suma, avg(amount) as średnia, min(amount) as minimum, max(amount) as maksimum from payment;
select avg(amount) as 'średnia wartość' from payment;
select count(*) from film where rating = 'G';
select count(*) from address where district = 'Buenos Aires' ;
select title, special_features from film where special_features like '%Trailers%' ;
select count(*) from film where length between 100 and 200;
select title from film where title like 'B_________';
select count(actor_id) from actor where last_name in ('Smith', 'Cage', 'Tracy');
select * from film where film_id limit 10;
select first_name, last_name from actor where last_name like 'Ber%';
select distinct first_name from actor where first_name like 'y%'; 